# Generated by Django 4.2.5 on 2023-10-06 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_productos', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=45)),
                ('emailProveedor', models.EmailField(max_length=45)),
                ('telefonoProveedor', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='SubtipoTransaccion',
            fields=[
                ('idSubtipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSubtipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Subtipo de Transacción',
                'verbose_name_plural': 'Subtipos de Transacción',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de Transacción',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('valorTotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('idProveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventario.proveedor')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.subtipotransaccion')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.AddField(
            model_name='subtipotransaccion',
            name='tipoTransaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.tipotransaccion'),
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('idExistencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fechaLlegada', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaVencimiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.producto')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.transaccion')),
            ],
            options={
                'verbose_name': 'Detalle de Transacción',
                'verbose_name_plural': 'Detalles de Transacción',
            },
        ),
    ]
