# Generated by Django 4.2.5 on 2023-11-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletransaccion',
            name='precioUnidad',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
