# Generated by Django 4.2.5 on 2023-11-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0003_proveedor_producto_idproveedor'),
        ('app_inventario', '0002_detalletransaccion_preciounidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_productos.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
