# Generated by Django 4.2.5 on 2023-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_alter_transaccion_idproveedor_delete_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelada'), ('E', 'Exitosa')], default='P', max_length=1),
        ),
    ]
