# Generated by Django 4.2.4 on 2023-08-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_productos.categoriaproducto')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
