# Generated by Django 4.2.5 on 2023-11-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=45)),
                ('emailProveedor', models.EmailField(max_length=45)),
                ('telefonoProveedor', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_productos.proveedor'),
        ),
    ]
