# Generated by Django 4.2.2 on 2023-12-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0004_rename_idproveedor_producto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='idProveedor',
        ),
    ]
